Add Aug 30, 2021 meeting notes
solid/authentication-panel pull request #190
Opened 2021-08-30 18:27 UTC by acoburn

This adds the minutes from the August 30, 2021, Solid Authentication Panel meeting.

2021-08-30 19:00 UTC, csarven commented on meetings/2021-08-30.md
> +# 2021-08-23 Solid Authentication
```suggestion
# 2021-08-30 Solid Authentication
```

2021-08-30 19:07 UTC, elf-pavlik approved these changes

2021-08-31 20:00 UTC, TallTed requested changes
typos and such

2021-08-31 20:00 UTC, TallTed commented on meetings/2021-08-30.md
> +not issue access tokens but just Id tokens. With that proposed architecture, there would be an association between
```suggestion
Pavlik: interesting. Have you looked at [draft PR 18](https://github.com/solid/solid-oidc/pull/18), where the IdP does
not issue access tokens but just ID tokens? With that proposed architecture, there would be an association between
```

2021-08-31 20:00 UTC, TallTed commented on meetings/2021-08-30.md
> +Given what Pavlik said that an IdP focuses only on identity, I would say that this is out-of-scope for Solid-OIDC.
```suggestion
Aaron: I see two question here. First, is it in scope for Solid-OIDC; and second, is it relevant for Solid?
Given what Pavlik said — that an IdP focuses only on identity — I would say that this is out-of-scope for Solid-OIDC.
```

2021-08-31 20:00 UTC, TallTed commented on meetings/2021-08-30.md
> +like it should be out of its scope.
```suggestion
Pavlik: it's important to clearly define the scope of Solid-OIDC. For example, issuing access
tokens seems like it should be out of its scope.
```

2021-08-31 20:00 UTC, TallTed commented on meetings/2021-08-30.md
> +in local storage. It is only used when performing silent authentication (i.e. when a user refreshes a webpage).
```suggestion
in local storage. It is only used when performing silent authentication (i.e., when a user refreshes a webpage).
```

2021-08-31 20:00 UTC, TallTed commented on meetings/2021-08-30.md
> +the Id token in a secure location (e.g. fetch closure).
```suggestion
the Id token in a secure location (e.g., fetch closure).
```

2021-08-31 20:00 UTC, TallTed commented on meetings/2021-08-30.md
> +Pavlik: we would need find consensus on this model: namely, that Solid-OIDC focuses only on Identity.
```suggestion
Pavlik: we would need to find consensus on this model: namely, that Solid-OIDC focuses only on Identity.
```

2021-08-31 20:00 UTC, TallTed commented on meetings/2021-08-30.md
> +We were discussing weather they may be some overarching best practice for Solid security.
```suggestion
We were discussing whether there may be some overarching best practice for Solid security.
```

2021-08-31 20:27 UTC, merged