Fix: refer to general and special CG meetings
solid/authentication-panel pull request #238
Opened 2023-09-12 16:15 UTC by woutermont

Action following multiple cases of uncertainty (cf. [matrix](https://matrix.to/#/!rUzJAFxzsTfTWEIQfp:gitter.im/$xEtmuBLbL7tVWIDI8gKVM1wh3u-LLlJIzLsJPOB674g?via=gitter.im&via=matrix.org&via=t2bot.io)), and looking ahead to the special topic meeting on this 2023-10-10. Can be reverted if decision turns out to keep panel meetings alive.

2023-09-17 22:22 UTC, csarven requested changes
This README needs a complete redo. Okay if for the time being, some of the below can be done in another PR.

* No need to continue to refer to panels.md because that'd likely be updated/removed - besides, it is fairly outdated/useless.
* Express that this panel repository is no longer active but here for the record and background information. Going forward, folks should move issues/PRs from this panel to specific repositories (as we've done it with, e.g., solid-oidc). The repository can eventually be archived.
* Remove the Projects section - don't waypoint to creating new issues.
* No need to mention meeting details. I think the last paragraph (line 45) works but I would've kept it simpler by just referring to the CG calendar and encourage using solid/specification Matrix chat.

2023-09-17 23:03 UTC, csarven approved these changes

2023-09-17 23:05 UTC, csarven commented
Decided to approve so to get something in quick/good enough.

2023-09-18 06:35 UTC, woutermont commented
Yes, agreed that the above should happen, probably as actions after the meeting of Oct 10th. 

This PR was just a quick fix to overcome confusion of partipants, so I suggest to merge it.

2023-09-27 09:47 UTC, csarven commented on README.md
> +Please refer to the Solid Community Group [calendar](https://www.w3.org/groups/cg/solid/calendar) and the Special Topic Meetings [schedule]([url](https://github.com/solid/specification/discussions/55
```suggestion
Please refer to the Solid Community Group [calendar](https://www.w3.org/groups/cg/solid/calendar) and the Special Topic Meetings [schedule]([url](https://github.com/solid/specification/discussions/555)) for more information. Every meeting is also announced on [Matrix](https://matrix.to/#/#solid_specification:gitter.im), with a link to its agenda. 
```

2023-09-27 09:47 UTC, merged