Use verifiable Identity Credential instead of Access Token
solid/authentication-panel pull request #94
Opened 2020-11-06 21:06 UTC by elf-pavlik

closes #60 

This is early version just so that we can have a reference for Monday's call. As you may see at this moment it only uses DPoP with IdP to bind Identity Credential to client's public key. When making request to RS i just uses JWS of the Verifiable Presentation.

I still need to write down example where more than one credentials are being presented by the client. Otherwise it may be hard to justify proposed changes.
As additional issue I would like to discuss exchanging Verifiable Presentation for simple Access Token in similar way as proposed in https://github.com/zenomt/webid-auth-protocol#token_pop_endpoint-api-parameters

2020-11-06 23:30 UTC, acoburn commented
Is the intent here to make DPoP and VC two possible mechanisms for authentication (with the idea that there could be more in the future)? Or is the intent to remove DPoP and replace it with VC (and have only a single mechanism for authentication)?

2020-11-07 01:55 UTC, elf-pavlik commented
As the draft currently stands it doesn't seem to address any authorization related requirements, including user constraining client's access (while not acting as resource controller), or client presenting specific verifiable credential (eg. membership) to gain access to a resource. At the same time current draft makes exclusive use of HTTP Authorization header by mandating it to include Access Token signed by IdP.
In current state of this PR it still relies on DPoP for binding VC to client's public key.

2020-11-07 15:18 UTC, acoburn requested changes
With [client identifiers](https://solid.github.io/authentication-panel/solid-oidc/#clientids), it is now possible for an authorization system to constrain access to apps. The current state of the AuthN spec makes it possible to address AuthZ use cases in the context of both WAC and [ACP](https://github.com/solid/authorization-panel/blob/master/proposals/acp/index.md).

Perhaps I am missing something significant, and I realize that this is still a draft, but this seems to be a dramatic departure from the last year of work on the AuthN specification. While I am entirely supportive of adding a mechanism for verifiable credentials, this seems to be taking the specification in a rather different direction. In fact, this seems like a rather significant rewrite of the spec itself.

I think that this might be better structured as a proposal _in addition to_ or _along side of_ the current recommendation. As a replacement, I don't see it as very tenable.

Specifically, what I would be interested in seeing is a proposal that either layers VC on top of the current DPoP access token structure or a proposal that is independent of DPoP in the same way that WebID-TLS is a mechanism that is independent of Solid-OIDC.

2020-11-07 20:22 UTC, dmitrizagidulin commented
Although I think that VCs make a better cross-domain identifier thant he global Access Token (which is why I had them in the previous draft), I suspect this proposal would be better in addition to, as opposed to instead of, the current access token structure.

2020-11-07 20:53 UTC, elf-pavlik commented
> Specifically, what I would be interested in seeing is a proposal that either layers VC on top of the current DPoP access token structure

I think with current draft, they only way to 'layer something on top', would require IdP to take responsibility of including more data in the access token. Since it is signed by IdP and RS needs to verify that signature, only IdP can include some additional claims (eg. VCs) in the Access Token. I think we need to decide if we want to have IdP with very limited responsibility and have other services taking other responsibilities, or IdP would be expected to handle various other responsibilities than OP.

2020-11-16 16:15 UTC, elf-pavlik commented
> @acoburn: I think that this might be better structured as a proposal in addition to or along side of the current recommendation.

>  @dmitrizagidulin: I suspect this proposal would be better in addition to, as opposed to instead of, the current access token structure.


Could you explain how do you see it used in addition? Especially if we would want to give additional responsibilities to party different than IdP, neither that extra party or the client can alter the Access Token in any way.

2020-11-16 16:36 UTC, acoburn commented
@elf-pavlik there are several possibilities (these are all just off the top of my head)

1. A secondary identity service could be used to exchange DPoP-bound access tokens for VC tokens.

Here, an agent would authenticate with an identity provider as per the current spec. The resulting access token can be given to a VC-capable service and exchanged for a new token. That new token would be given to the resource server. This approach is more of a _layering_ on top of the existing spec flows.

2. A VC-capable identity provider would exist in place of the current OIDC-based flows.

Here, there would be no OIDC access token (from the current spec); only the VC token would be given to a client app.

---

In both cases, resource servers would use different mechanisms for validating these incoming tokens: `webid` claims + DPoP confirmation for the `Solid-WebId` approach; VC identifiers for this new approach. It will be crucial for resource servers to be able to (a) distinguish between these different token types and (b) advertise support for these different mechanisms.

2021-01-04 13:57 UTC, elf-pavlik commented
I think IdP might need to be responsible for provide any needed credential to the client and changes in this PR don't go in that direction. Just as user would want to set restrictions on what client can access (we can think OAuth scopes), user would also want to have control over which credentials client can get to use when accessing resources.

2021-01-04 13:57 UTC, closed without merging